APPLICATION = homie-pwmctrl
BOARD = homie-pwmctrl
RIOTBASE = $(CURDIR)/../../../firmware/RIOT
CONFIG ?= default.config
KCONFIG_ADD_CONFIG += $(CURDIR)/$(CONFIG)

include $(RIOTBASE)/../app/Makefile.include