APPLICATION = homie-switchy-rgb
BOARD = homie-switchy-rgb
RIOTBASE = $(CURDIR)/../../../firmware/RIOT
CONFIG ?= default.config
KCONFIG_ADD_CONFIG += $(CURDIR)/$(CONFIG)

include $(RIOTBASE)/../app/Makefile.include
